[package]
name = "kucoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kucoin_rs = "0.4.4"
log = "0.4"
chrono = "0.4"
env_logger = "0.9.1"
